Reading for 1.5.5 and migrating to the new csproj format
Annosz/UIInfoSuite2 pull request #66
Opened 2021-08-28 02:57 UTC by strobel1ght

2021-08-28 07:34 UTC, Annosz commented
Thanks!

2021-09-12 10:22 UTC, Deflaktor requested changes

2021-09-12 10:22 UTC, Deflaktor commented on UIInfoSuite2/UIInfoSuite2.csproj
> +    <Platforms>AnyCPU</Platforms>
Platforms and PlatformTarget properties can be removed

2021-09-12 10:22 UTC, Deflaktor commented on UIInfoSuite2/manifest.json
>      "EntryDll": "UIInfoSuite2.dll",
Increase MinimumApiVersion from 3.0.0 to 3.13.0

2021-09-12 10:22 UTC, Deflaktor commented on UIInfoSuite2/UIInfoSuite2.csproj
> -  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
Since the x86 TargetProfile has been removed, it needs to be removed from the UIInfoSuite2.sln file as well

2021-12-11 19:21 UTC, Annosz commented
Thanks for the work! Now that the 1.5.5 version is out, I implemented the changes, but sadly, I had to make a new pull request, because this one already had some merge conflicts. But your work showed me what I need to do, so huge thanks! :)

2021-12-11 19:21 UTC, closed without merging

2021-12-24 21:45 UTC, Zamiell commented
I just wanted to say thank you Ishan and Annosz for all of your work!